version: '3.4'

services:
  portainer:
    image: portainer/portainer-ce
    restart: always

  catalogdb:
    image: mongo
    restart: always
  
  mongo-express:
    image: mongo-express
    restart: always
  
  basketdb:
    image: redis:alpine
    restart: always

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always

  discountdb:
    image: postgres
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    restart: always

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

volumes:
  mongo_data: 
  portainer_data:
  redis_data:
  redis-config:
  postgres_data:
  pgadmin_data:
