version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--port", "27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  mongo-express:
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: catalogdb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_URL: mongodb://root:example@catalogdb:27017/
    depends_on:
      - catalogdb

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=mongodb://root:example@catalogdb:27017"
      - "IsInDocker=true" 
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - "9000:80"
    depends_on:
      - catalogdb
